version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.7
      - test-3.8
      - test-3.9
      - mypy
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6.13-buster
    working_directory: ~/valohai/valohai-cli
    parallelism: 1
    shell: /bin/bash --login
    environment: &env-template
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      PIP_EXISTS_ACTION: w
      EMAIL: foo@example.com
      GIT_AUTHOR_NAME: Foo Bar
      GIT_COMMITTER_NAME: Foo Bar
      TOX_ENV: py36
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-master-
        - v1-dep-
    - run: sudo pip install -U pip setuptools wheel tox coverage
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.cache/pip
        - ~/.pyenv
    - setup_remote_docker
    - run: tox -e $TOX_ENV -- --cov . --cov-report term-missing --junitxml=$CIRCLE_TEST_REPORTS/junit.xml -ra
    - run: bash <(curl -s https://codecov.io/bash) -t 624f70bb-b7c4-4972-ba3f-f90923b8840c
    - store_test_results:
        path: /tmp/circleci-test-results
  test-3.7:
    <<: *test-template
    environment:
      <<: *env-template
      TOX_ENV: py37
    docker:
      - image: circleci/python:3.7.10-buster
  test-3.8:
    <<: *test-template
    environment:
      <<: *env-template
      TOX_ENV: py37
    docker:
      - image: circleci/python:3.8.8-buster
  test-3.9:
    <<: *test-template
    environment:
      <<: *env-template
      TOX_ENV: py39
    docker:
      - image: circleci/python:3.9.2-buster
  mypy:
    docker:
      - image: circleci/python:3.9.2-buster
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-mypy-dep-{{ .Branch }}-
        - v1-mypy-dep-master-
        - v1-mypy-dep-
    - run: pip install -U pip setuptools wheel tox coverage
    - run: pip install -r requirements-typecheck.txt
    - save_cache:
        key: v1-mypy-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.cache/pip
    - run: make mypy
