name: CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Test:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        python-version:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@v2
      - run: pip install -U pip setuptools wheel
      - run: 'pip install -e . -r requirements-dev.txt'
      - run: make test
        env:
          EMAIL: foo@example.com
          GIT_AUTHOR_NAME: Foo Bar
          GIT_COMMITTER_NAME: Foo Bar
      - uses: codecov/codecov-action@v2
  Lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - run: pip install -U pip setuptools wheel
      - run: 'pip install -r requirements-dev.txt'
      - run: make lint
  Mypy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - run: pip install -U pip setuptools wheel
      - run: 'pip install -e .'
      - run: 'pip install -r requirements-typecheck.txt'
      - run: make mypy
